services:
    marmelab.ng_admin_generator.entity_configuration_retriever:
        class: marmelab\NgAdminGeneratorBundle\Retriever\EntityConfigurationRetriever
        arguments:
            - @doctrine.orm.entity_manager
