services:
    marmelab.ng_admin_generator.configuration_generator:
        class: marmelab\NgAdminGeneratorBundle\Generator\ConfigurationGenerator
        arguments:
            -   # Transformers: be careful, order matters!
                - @marmelab.ng_admin_generator.transformer.doctrine_to_ngadmin
                - @marmelab.ng_admin_generator.entity_referenced_field_name_to_meaningful_name
                - @marmelab.ng_admin_generator.entity_to_entity_without_excluded_fields
                - @marmelab.ng_admin_generator.entity_to_entity_with_icon
            - @doctrine.orm.entity_manager
            - @twig

    marmelab.ng_admin_generator.transformer.doctrine_to_ngadmin:
        class: marmelab\NgAdminGeneratorBundle\Transformer\DoctrineToNgAdminTransformer
        public: false

    marmelab.ng_admin_generator.entity_referenced_field_name_to_meaningful_name:
        class: marmelab\NgAdminGeneratorBundle\Transformer\EntityReferencedFieldNameToMeaningfulNameTransformer
        public: false
        arguments:
            - @doctrine.orm.entity_manager

    marmelab.ng_admin_generator.entity_to_entity_without_excluded_fields:
        class: marmelab\NgAdminGeneratorBundle\Transformer\EntityToEntityWithoutExcludedFieldsTransformer
        public: false
        arguments:
            - @jms_serializer

    marmelab.ng_admin_generator.entity_to_entity_with_icon:
        class: marmelab\NgAdminGeneratorBundle\Transformer\EntityToEntityWithIconTransformer
        public: false
        arguments:
            - %ng_admin_generator.icons%
